name: "API: Format Sort"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.8"

      - uses: yezz123/setup-uv@v4

      - run: uv sync

      - run: source .venv/bin/activate && ruff check --select I .
