name: "API: OpenAPI"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - uses: yezz123/setup-uv@v4

      - name: Check if openapi.json exists
        run: |
          if [ ! -f "openapi.json" ]; then   
              echo "openapi.json does not exist"
              exit 1
          else
              echo "openapi.json exists"
          fi

      - name: Generate openapi.json
        run: python manage.py generate_openapi --directory ./generated

      - name: Check that openapi.json is up to date
        run: |
          diff -u ./openapi.json ./generated/openapi.json
          if [ $? -ne 0 ]; then
              echo "openapi.json is not up to date"
              exit 1
          else
              echo "openapi.json is up to date"
          fi
