name: Python with uv
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      uv-version:
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./apps/api
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: yezz123/setup-uv@v4
      with:
        uv-version: ${{ inputs.uv-version }}

    - name: Install dependencies
      run: uv sync
